In [2]:
import numpy as np

# 未确认勘误

## 第77页

错误内容：np.partition()的输入是数组和数字K，输出结果是一个新数组，最左边是第K小的值，往右是任意顺序的其他值。

应改为：根据源代码里面给出的内容，K值的含义应该是分割点，而不是最左边是第K小的值，这个函数就是类似于快速排序的特点，K位置左边的值均小于K位置右边的值


![](https://raw.githubusercontent.com/muxuezi/pdsh/master/WechatIMG3.png)

In [3]:
np.partition?

In [ ]:
Signature: np.partition(a, kth, axis=-1, kind='introselect', order=None)
Docstring:
Return a partitioned copy of an array.

Creates a copy of the array with its elements rearranged in such a
way that the value of the element in k-th position is in the
position it would be in a sorted array. All elements smaller than
the k-th element are moved before this element and all equal or
greater are moved behind it. The ordering of the elements in the two
partitions is undefined.

.. versionadded:: 1.8.0

Parameters
----------
a : array_like
    Array to be sorted.
kth : int or sequence of ints
    Element index to partition by. The k-th value of the element
    will be in its final sorted position and all smaller elements
    will be moved before it and all equal or greater elements behind
    it. The order of all elements in the partitions is undefined. If
    provided with a sequence of k-th it will partition all elements
    indexed by k-th  of them into their sorted position at once.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'introselect'}, optional
    Selection algorithm. Default is 'introselect'.
order : str or list of str, optional
    When `a` is an array with fields defined, this argument
    specifies which fields to compare first, second, etc.  A single
    field can be specified as a string.  Not all fields need be
    specified, but unspecified fields will still be used, in the
    order in which they come up in the dtype, to break ties.

Returns
-------
partitioned_array : ndarray
    Array of the same type and shape as `a`.

See Also
--------
ndarray.partition : Method to sort an array in-place.
argpartition : Indirect partition.
sort : Full sorting

Notes
-----
The various selection algorithms are characterized by their average
speed, worst case performance, work space size, and whether they are
stable. A stable sort keeps items with the same key in the same
relative order. The available algorithms have the following
properties:

================= ======= ============= ============ =======
   kind            speed   worst case    work space  stable
================= ======= ============= ============ =======
'introselect'        1        O(n)           0         no
================= ======= ============= ============ =======

All the partition algorithms make temporary copies of the data when
partitioning along any but the last axis.  Consequently,
partitioning along the last axis is faster and uses less space than
partitioning along any other axis.

The sort order for complex numbers is lexicographic. If both the
real and imaginary parts are non-nan then the order is determined by
the real parts except when they are equal, in which case the order
is determined by the imaginary parts.

Examples
--------
>>> a = np.array([3, 4, 2, 1])
>>> np.partition(a, 3)
array([2, 1, 3, 4])

>>> np.partition(a, (1, 3))
array([1, 2, 3, 4])
File:      ~/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py
Type:      function

In [2]:
M=np.random.randint(0,10,size=(3,6))
M

array([[0, 9, 4, 1, 6, 6],
       [9, 7, 8, 5, 3, 0],
       [5, 2, 7, 2, 9, 2]])

In [3]:
np.partition(M,2)

array([[0, 1, 4, 9, 6, 6],
       [0, 3, 5, 8, 7, 9],
       [2, 2, 2, 5, 9, 7]])

In [4]:
np.partition(M,3)

array([[1, 0, 4, 6, 6, 9],
       [0, 3, 5, 7, 8, 9],
       [2, 2, 2, 5, 9, 7]])